version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # VITE_API_BASE_URL untuk build dan runtime
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "80:80"
    environment:
      # VITE_API_BASE_URL untuk nginx proxy dari environment variable
      # Gunakan: docker-compose --env-file .env.local up
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    restart: unless-stopped

  # Contoh jika ingin menjalankan backend juga
  # backend:
  #   image: your-backend-image:latest
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #   restart: unless-stopped 