export const STATUS = {
  STATUS_PEMINJAMAN: {
    DIPROSES: "DIPROSES",
    DISETUJUI: "DISETUJUI",
    DITOLAK: "DITOLAK",
    SELESAI: "SELESAI",
  },
  STATUS_TRANSAKSI: {
    PAID: "PAID",
    PENDING: "PENDING",
    CANCELED: "CANCELED",
    REFUNDED: "REFUNDED",
    PARTIAL_REFUNDED: "PARTIAL_REFUNDED",
    CHECKOUT: "CHECKOUT",
  },
  STATUS_NOTIF: {
    PEMBAYARAN: "PEMBAYARAN",
    PEMINJAMAN: "PEMINJAMAN",
  },
  TIPEUSER: {
    INUNAND: "INUNAND",
    EXUNAND: "EXUNAND",
  },
  ROLE: {
    PEMINJAM: "PEMINJAM",
    ADMIN: "ADMIN",
  },
};

