name: Deploy Frontend to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'fe/**'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: pbf-frontend
  REGION: asia-southeast2
  REGISTRY_URL: asia-southeast2-docker.pkg.dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use gcloud as credential helper
      run: |
        gcloud auth configure-docker
        gcloud auth configure-docker $REGISTRY_URL

    - name: Create Artifact Registry repository if not exists
      run: |
        gcloud artifacts repositories create $SERVICE_NAME \
          --repository-format=docker \
          --location=$REGION \
          --description="Docker repository for $SERVICE_NAME" || echo "Repository already exists"

    - name: Build Docker image
      run: |
        cd fe
        docker build \
          --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
          --build-arg VITE_PUSHER_KEY=${{ secrets.VITE_PUSHER_KEY }} \
          --build-arg VITE_PUSHER_CLUSTER=${{ secrets.VITE_PUSHER_CLUSTER }} \
          -t $REGISTRY_URL/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA \
          -t $REGISTRY_URL/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:latest .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push $REGISTRY_URL/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA
        docker push $REGISTRY_URL/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image $REGISTRY_URL/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --port 80 \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --set-env-vars="NODE_ENV=production"

    - name: Get Cloud Run URL
      run: |
        URL=$(gcloud run services describe $SERVICE_NAME --region $REGION --format 'value(status.url)')
        echo "Frontend deployed to: $URL" 