name: Deploy Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fe-app:latest
        build-args: |
          VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Stop existing container
          docker stop fe-app || true
          docker rm fe-app || true
          
          # Pull latest image
          docker pull ${{ secrets.DOCKER_USERNAME }}/fe-app:latest
          
          # Run new container dengan VITE_API_BASE_URL dari secrets
          # IP backend akan aman disimpan di GitHub secrets
          docker run -d \
            --name fe-app \
            -p 80:80 \
            -e VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} \
            ${{ secrets.DOCKER_USERNAME }}/fe-app:latest 